// Generated by tool/generate_ast.py

namespace DotLox;

public abstract class Expr {

	public abstract T Accept<T>(Visitor<T> visitor);

	public interface Visitor<T> {
		public T VisitAssignExpr(Assign expr);
		public T VisitBinaryExpr(Binary expr);
		public T VisitCallExpr(Call expr);
		public T VisitGetExpr(Get expr);
		public T VisitGroupingExpr(Grouping expr);
		public T VisitLiteralExpr(Literal expr);
		public T VisitLogicalExpr(Logical expr);
		public T VisitSetExpr(Set expr);
		public T VisitSuperExpr(Super expr);
		public T VisitThisExpr(This expr);
		public T VisitUnaryExpr(Unary expr);
		public T VisitVariableExpr(Variable expr);
	}

	public class Assign : Expr {

		readonly Token name;
		readonly Expr value;

		public Token getName() {
			return name;
		}

		public Expr getValue() {
			return value;
		}

		public Assign(Token name, Expr value) {
			this.name = name;
			this.value = value;
		}

		public override T Accept<T>(Visitor<T> visitor) {
			return visitor.VisitAssignExpr(this);
		}
	}

	public class Binary : Expr {

		readonly Expr left;
		readonly Token opr;
		readonly Expr right;

		public Expr getLeft() {
			return left;
		}

		public Token getOpr() {
			return opr;
		}

		public Expr getRight() {
			return right;
		}

		public Binary(Expr left, Token opr, Expr right) {
			this.left = left;
			this.opr = opr;
			this.right = right;
		}

		public override T Accept<T>(Visitor<T> visitor) {
			return visitor.VisitBinaryExpr(this);
		}
	}

	public class Call : Expr {

		readonly Expr callee;
		readonly Token paren;
		readonly List<Expr> arguments;

		public Expr getCallee() {
			return callee;
		}

		public Token getParen() {
			return paren;
		}

		public List<Expr> getArguments() {
			return arguments;
		}

		public Call(Expr callee, Token paren, List<Expr> arguments) {
			this.callee = callee;
			this.paren = paren;
			this.arguments = arguments;
		}

		public override T Accept<T>(Visitor<T> visitor) {
			return visitor.VisitCallExpr(this);
		}
	}

	public class Get : Expr {

		readonly Expr obj;
		readonly Token name;

		public Expr getObj() {
			return obj;
		}

		public Token getName() {
			return name;
		}

		public Get(Expr obj, Token name) {
			this.obj = obj;
			this.name = name;
		}

		public override T Accept<T>(Visitor<T> visitor) {
			return visitor.VisitGetExpr(this);
		}
	}

	public class Grouping : Expr {

		readonly Expr expression;

		public Expr getExpression() {
			return expression;
		}

		public Grouping(Expr expression) {
			this.expression = expression;
		}

		public override T Accept<T>(Visitor<T> visitor) {
			return visitor.VisitGroupingExpr(this);
		}
	}

	public class Literal : Expr {

		readonly Object? value;

		public Object? getValue() {
			return value;
		}

		public Literal(Object? value) {
			this.value = value;
		}

		public override T Accept<T>(Visitor<T> visitor) {
			return visitor.VisitLiteralExpr(this);
		}
	}

	public class Logical : Expr {

		readonly Expr left;
		readonly Token opr;
		readonly Expr right;

		public Expr getLeft() {
			return left;
		}

		public Token getOpr() {
			return opr;
		}

		public Expr getRight() {
			return right;
		}

		public Logical(Expr left, Token opr, Expr right) {
			this.left = left;
			this.opr = opr;
			this.right = right;
		}

		public override T Accept<T>(Visitor<T> visitor) {
			return visitor.VisitLogicalExpr(this);
		}
	}

	public class Set : Expr {

		readonly Expr obj;
		readonly Token name;
		readonly Expr value;

		public Expr getObj() {
			return obj;
		}

		public Token getName() {
			return name;
		}

		public Expr getValue() {
			return value;
		}

		public Set(Expr obj, Token name, Expr value) {
			this.obj = obj;
			this.name = name;
			this.value = value;
		}

		public override T Accept<T>(Visitor<T> visitor) {
			return visitor.VisitSetExpr(this);
		}
	}

	public class Super : Expr {

		readonly Token keyword;
		readonly Token method;

		public Token getKeyword() {
			return keyword;
		}

		public Token getMethod() {
			return method;
		}

		public Super(Token keyword, Token method) {
			this.keyword = keyword;
			this.method = method;
		}

		public override T Accept<T>(Visitor<T> visitor) {
			return visitor.VisitSuperExpr(this);
		}
	}

	public class This : Expr {

		readonly Token keyword;

		public Token getKeyword() {
			return keyword;
		}

		public This(Token keyword) {
			this.keyword = keyword;
		}

		public override T Accept<T>(Visitor<T> visitor) {
			return visitor.VisitThisExpr(this);
		}
	}

	public class Unary : Expr {

		readonly Token opr;
		readonly Expr right;

		public Token getOpr() {
			return opr;
		}

		public Expr getRight() {
			return right;
		}

		public Unary(Token opr, Expr right) {
			this.opr = opr;
			this.right = right;
		}

		public override T Accept<T>(Visitor<T> visitor) {
			return visitor.VisitUnaryExpr(this);
		}
	}

	public class Variable : Expr {

		readonly Token name;

		public Token getName() {
			return name;
		}

		public Variable(Token name) {
			this.name = name;
		}

		public override T Accept<T>(Visitor<T> visitor) {
			return visitor.VisitVariableExpr(this);
		}
	}

}
